"""
Convert SFINCS map output (sfincs_map.nc) to mSWE-GNN .pkl datasets
using an existing mesh template generated by create_mesh_template_marg.py.

Usage:
    python database/convert_sfincs_to_pkl_marg.py \
      --sfincs-map "C:/.../sfincs_map.nc" \
      --template-pkl "database/datasets/train/template_marg.pkl" \
      --dataset-name "sfincs_marg" \
      --out-root "database/datasets"

Outputs:
    database/datasets/train/<dataset-name>.pkl
    database/datasets/test/<dataset-name>.pkl
"""

import argparse
import copy
import os
import pickle

import numpy as np
import torch
import xarray as xr
from scipy.interpolate import griddata


def load_single_data_object(template_pkl_path):
    with open(template_pkl_path, "rb") as f:
        dataset = pickle.load(f)

    if not isinstance(dataset, list) or len(dataset) == 0:
        raise RuntimeError("Template .pkl must contain a non-empty list of Data objects.")

    return dataset[0]


def get_target_points(template_data):
    if not hasattr(template_data, "mesh"):
        raise RuntimeError("Template Data object must include a mesh attribute.")

    mesh = template_data.mesh
    if not hasattr(mesh, "face_xy"):
        raise RuntimeError("Template mesh must include face_xy coordinates.")

    target_points = np.asarray(mesh.face_xy)
    if target_points.ndim != 2 or target_points.shape[1] != 2:
        raise RuntimeError("mesh.face_xy must be an array of shape [num_faces, 2].")

    return target_points


def get_source_points(ds, x_var="x", y_var="y"):
    if x_var not in ds.coords or y_var not in ds.coords:
        raise RuntimeError(f"Could not find coordinates '{x_var}' and '{y_var}' in dataset coords.")

    x = ds.coords[x_var].values
    y = ds.coords[y_var].values

    if x.ndim == 2 and y.ndim == 2:
        return np.column_stack([x.reshape(-1), y.reshape(-1)])

    if x.ndim == 1 and y.ndim == 1:
        xx, yy = np.meshgrid(x, y, indexing="ij")
        return np.column_stack([xx.reshape(-1), yy.reshape(-1)])

    raise RuntimeError("Unsupported coordinate dimensions for x/y. Expected both 2D or both 1D.")


def interpolate_time_series(source_points, grid_3d, target_points, label):
    """
    Interpolate a time-varying gridded field [T, N, M] onto target points [K, 2].
    Returns array [K, T].
    """
    if grid_3d.ndim != 3:
        raise RuntimeError(f"{label} must be a 3D array [time, n, m].")

    time_steps = grid_3d.shape[0]
    num_targets = target_points.shape[0]
    out = np.zeros((num_targets, time_steps), dtype=np.float32)

    for t in range(time_steps):
        values = grid_3d[t].reshape(-1)
        valid = np.isfinite(values)

        if valid.sum() == 0:
            continue

        # First pass: linear interpolation for smoothness
        interp_linear = griddata(
            source_points[valid],
            values[valid],
            target_points,
            method="linear",
        )

        # Fill any outside-domain NaNs with nearest interpolation
        nan_mask = ~np.isfinite(interp_linear)
        if nan_mask.any():
            interp_nearest = griddata(
                source_points[valid],
                values[valid],
                target_points[nan_mask],
                method="nearest",
            )
            interp_linear[nan_mask] = interp_nearest

        interp_linear = np.nan_to_num(interp_linear, nan=0.0)
        out[:, t] = interp_linear.astype(np.float32)

    return out


def build_output_data(template_data, WD, VX, VY):
    data = copy.deepcopy(template_data)

    num_nodes = data.num_nodes if isinstance(data.num_nodes, int) else int(data.num_nodes)

    if WD.shape[0] != num_nodes or VX.shape[0] != num_nodes or VY.shape[0] != num_nodes:
        raise RuntimeError("Interpolated arrays do not match template num_nodes.")

    data.WD = torch.FloatTensor(WD)
    data.VX = torch.FloatTensor(VX)
    data.VY = torch.FloatTensor(VY)

    # Rebuild BC tensor horizon to match new time length.
    time_steps = WD.shape[1]
    if hasattr(data, "node_BC"):
        n_bc = int(data.node_BC.shape[0])
        data.BC = torch.zeros((n_bc, time_steps, 2), dtype=torch.float32)

    return data


def main():
    parser = argparse.ArgumentParser(description="Convert SFINCS map output to mSWE-GNN .pkl datasets")
    parser.add_argument("--sfincs-map", required=True, help="Path to sfincs_map.nc")
    parser.add_argument("--template-pkl", required=True, help="Path to template .pkl with mesh topology")
    parser.add_argument("--dataset-name", default="sfincs_marg", help="Output dataset name for train/test pkl")
    parser.add_argument("--out-root", default="database/datasets", help="Root dataset folder containing train/test")
    parser.add_argument("--x-var", default="x", help="x coordinate variable name")
    parser.add_argument("--y-var", default="y", help="y coordinate variable name")
    parser.add_argument("--water-level-var", default="zs", help="Water level variable name (surface elevation)")
    parser.add_argument("--bed-level-var", default="zb", help="Bed elevation variable name")
    parser.add_argument("--vx-var", default=None, help="Optional velocity-x variable name")
    parser.add_argument("--vy-var", default=None, help="Optional velocity-y variable name")
    args = parser.parse_args()

    if not os.path.exists(args.sfincs_map):
        raise FileNotFoundError(f"SFINCS map file not found: {args.sfincs_map}")
    if not os.path.exists(args.template_pkl):
        raise FileNotFoundError(f"Template .pkl not found: {args.template_pkl}")

    print("Loading template mesh...")
    template_data = load_single_data_object(args.template_pkl)
    target_points = get_target_points(template_data)
    print(f"  Target mesh nodes (faces): {target_points.shape[0]}")

    print("Opening SFINCS map...")
    ds = xr.open_dataset(args.sfincs_map)

    if args.water_level_var not in ds.data_vars:
        raise RuntimeError(f"Water level variable '{args.water_level_var}' not found in sfincs_map.nc")
    if args.bed_level_var not in ds.data_vars:
        raise RuntimeError(f"Bed level variable '{args.bed_level_var}' not found in sfincs_map.nc")

    source_points = get_source_points(ds, x_var=args.x_var, y_var=args.y_var)
    print(f"  Source grid points: {source_points.shape[0]}")

    zs = ds[args.water_level_var].values  # [time, n, m]
    zb = ds[args.bed_level_var].values    # [n, m]

    if zs.ndim != 3 or zb.ndim != 2:
        raise RuntimeError("Expected zs [time,n,m] and zb [n,m].")

    print("Computing water depth WD = max(zs - zb, 0)...")
    WD_grid = np.maximum(zs - zb[None, :, :], 0.0).astype(np.float32)

    print("Interpolating WD to mesh...")
    WD = interpolate_time_series(source_points, WD_grid, target_points, "WD")

    # Velocities are optional in this SFINCS output. Use zeros if missing.
    if args.vx_var is not None and args.vx_var in ds.data_vars:
        print(f"Interpolating velocity X from '{args.vx_var}'...")
        VX_grid = ds[args.vx_var].values
        VX = interpolate_time_series(source_points, VX_grid, target_points, "VX")
    else:
        VX = np.zeros_like(WD, dtype=np.float32)
        print("Velocity X not provided; using zeros.")

    if args.vy_var is not None and args.vy_var in ds.data_vars:
        print(f"Interpolating velocity Y from '{args.vy_var}'...")
        VY_grid = ds[args.vy_var].values
        VY = interpolate_time_series(source_points, VY_grid, target_points, "VY")
    else:
        VY = np.zeros_like(WD, dtype=np.float32)
        print("Velocity Y not provided; using zeros.")

    data_out = build_output_data(template_data, WD=WD, VX=VX, VY=VY)

    train_dir = os.path.join(args.out_root, "train")
    test_dir = os.path.join(args.out_root, "test")
    os.makedirs(train_dir, exist_ok=True)
    os.makedirs(test_dir, exist_ok=True)

    train_path = os.path.join(train_dir, f"{args.dataset_name}.pkl")
    test_path = os.path.join(test_dir, f"{args.dataset_name}.pkl")

    # Inference-only path: save same sample for train/test so scaler pipeline works.
    with open(train_path, "wb") as f:
        pickle.dump([data_out], f)
    with open(test_path, "wb") as f:
        pickle.dump([copy.deepcopy(data_out)], f)

    print("Done.")
    print(f"  Train dataset: {train_path}")
    print(f"  Test dataset:  {test_path}")
    print(f"  WD shape:      {tuple(data_out.WD.shape)}")
    print(f"  VX shape:      {tuple(data_out.VX.shape)}")
    print(f"  VY shape:      {tuple(data_out.VY.shape)}")


if __name__ == "__main__":
    main()
