"""
Convert SFINCS map output (sfincs_map.nc) to mSWE-GNN .pkl datasets
using an existing mesh template generated by create_mesh_template_marg.py.

Usage:
    python database/convert_sfincs_to_pkl_marg.py \
      --sfincs-map "C:/.../sfincs_map.nc" \
      --template-pkl "database/datasets/train/template_marg.pkl" \
      --dataset-name "sfincs_marg" \
      --out-root "database/datasets"

Outputs:
    database/datasets/train/<dataset-name>.pkl
    database/datasets/test/<dataset-name>.pkl
"""

import argparse
import copy
import os
import pickle
import sys

# Templates carry Mesh/MultiscaleMesh objects pickled under database.graph_creation
# (see create_mesh_template_marg.py). When this script is run directly
# (`python database/convert_sfincs_to_pkl_marg.py ...`), Python only puts this
# script's own directory on sys.path, not the repo root - without the repo root here
# too, `import database` fails while unpickling the template.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

import numpy as np
import torch
import xarray as xr
from scipy.interpolate import griddata, interp1d


def load_single_data_object(template_pkl_path):
    with open(template_pkl_path, "rb") as f:
        dataset = pickle.load(f)

    if not isinstance(dataset, list) or len(dataset) == 0:
        raise RuntimeError("Template .pkl must contain a non-empty list of Data objects.")

    return dataset[0]


def get_target_points(template_data):
    if not hasattr(template_data, "mesh"):
        raise RuntimeError("Template Data object must include a mesh attribute.")

    mesh = template_data.mesh
    if not hasattr(mesh, "face_xy"):
        raise RuntimeError("Template mesh must include face_xy coordinates.")

    target_points = np.asarray(mesh.face_xy)
    if target_points.ndim != 2 or target_points.shape[1] != 2:
        raise RuntimeError("mesh.face_xy must be an array of shape [num_faces, 2].")

    return target_points


def get_source_points(ds, x_var="x", y_var="y"):
    if x_var not in ds.coords or y_var not in ds.coords:
        raise RuntimeError(f"Could not find coordinates '{x_var}' and '{y_var}' in dataset coords.")

    x = ds.coords[x_var].values
    y = ds.coords[y_var].values

    if x.ndim == 2 and y.ndim == 2:
        return np.column_stack([x.reshape(-1), y.reshape(-1)])

    if x.ndim == 1 and y.ndim == 1:
        xx, yy = np.meshgrid(x, y, indexing="ij")
        return np.column_stack([xx.reshape(-1), yy.reshape(-1)])

    raise RuntimeError("Unsupported coordinate dimensions for x/y. Expected both 2D or both 1D.")


def interpolate_time_series(source_points, grid_3d, target_points, label):
    """
    Interpolate a time-varying gridded field [T, N, M] onto target points [K, 2].
    Returns array [K, T].
    """
    if grid_3d.ndim != 3:
        raise RuntimeError(f"{label} must be a 3D array [time, n, m].")

    time_steps = grid_3d.shape[0]
    num_targets = target_points.shape[0]
    out = np.zeros((num_targets, time_steps), dtype=np.float32)

    for t in range(time_steps):
        values = grid_3d[t].reshape(-1)
        valid = np.isfinite(values)

        if valid.sum() == 0:
            continue

        # First pass: linear interpolation for smoothness
        interp_linear = griddata(
            source_points[valid],
            values[valid],
            target_points,
            method="linear",
        )

        # Mesh nodes outside the convex hull of wet source cells get NaN from
        # linear griddata.  Set them to 0 (dry) instead of nearest-neighbour,
        # which would otherwise flood every dry hillslope node with the value
        # of the nearest wet river cell.
        interp_linear = np.nan_to_num(interp_linear, nan=0.0)
        out[:, t] = interp_linear.astype(np.float32)

    return out


def parse_src_file(src_path):
    """Read SFINCS source file: returns array of shape [n_src, 2] (x, y) in model CRS."""
    pts = []
    with open(src_path, encoding='latin-1') as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) >= 2:
                try:
                    pts.append([float(parts[0]), float(parts[1])])
                except ValueError:
                    continue
    return np.array(pts, dtype=np.float64)


def parse_dis_file(dis_path):
    """Read SFINCS discharge file (time[s], q1, q2, ...).
    Returns (time_s [T], discharge [T, n_src]).

    NaN entries (e.g. a source time series shorter than the .dis time axis,
    padded with NaN) are forward-filled per column with the last valid value,
    so out-of-range interpolation fills never propagate NaN into the BC.
    """
    data = np.loadtxt(dis_path)
    time_s = data[:, 0]
    discharge = data[:, 1:].astype(np.float32)

    if np.isnan(discharge).any():
        for i in range(discharge.shape[1]):
            col = discharge[:, i]
            nan_mask = np.isnan(col)
            if nan_mask.any():
                valid_idx = np.flatnonzero(~nan_mask)
                if len(valid_idx) == 0:
                    raise ValueError(f"{dis_path}: source column {i} is all NaN")
                pos = np.searchsorted(valid_idx, np.flatnonzero(nan_mask), side='right') - 1
                # NaN before the first valid value: fall back to the first valid value
                filled_idx = valid_idx[pos.clip(min=0)]
                discharge[nan_mask, i] = col[filled_idx]
                print(f"  parse_dis_file: source column {i} had {nan_mask.sum()} NaN(s) "
                      f"(t {time_s[nan_mask].min():.0f}-{time_s[nan_mask].max():.0f} s) - forward-filled")

    return time_s, discharge


def find_nearest_mesh_nodes(source_xy, face_xy):
    """Return indices of nearest face-center nodes for each source point."""
    from scipy.spatial import cKDTree
    tree = cKDTree(face_xy)
    _, indices = tree.query(source_xy)
    return indices.astype(np.int32)


def parse_weir_file(weir_path):
    """Read a SFINCS weir file: one or more named polylines, each point as
    "x y crest_z discharge_coef". Returns a list of dicts:
        {'name': str, 'xy': [N,2] array, 'z': [N] array}
    """
    with open(weir_path, encoding='latin-1') as f:
        lines = [l.strip() for l in f if l.strip()]

    weirs = []
    i = 0
    while i < len(lines):
        name = lines[i]
        i += 1
        n_points, n_cols = (int(v) for v in lines[i].split()[:2])
        i += 1
        pts = np.array([[float(v) for v in lines[i + k].split()[:n_cols]] for k in range(n_points)])
        i += n_points
        weirs.append({'name': name, 'xy': pts[:, :2], 'z': pts[:, 2]})
    return weirs


def compute_edge_weir_crest_offset(data, weirs, tol=None):
    """Per-(dual-edge) "barrier height above local terrain" feature for one
    structures scenario, aligned to data.edge_index / data.face_distance /
    data.edge_slope (same flat, per-scale-concatenated ordering built by
    MultiscaleMesh.stack_meshes).

    For every primal mesh edge that coincides with one of this scenario's own
    weir lines (embedded as a constrained CDT edge when the shared structures
    template was built), the dual edge connecting the two faces sharing that
    primal edge gets max(0, crest_z - avg(DEM of the two faces)), i.e. how
    much higher the crest is than the surrounding terrain (0 = no barrier).
    Every other dual edge - including the entirety of edge_weir_crest for
    events with no structures at all - stays 0.

    data: Data object with data.mesh a MultiscaleMesh built from the shared
        structures template. build_output_data() leaves data.DEM/data.mesh
        untouched (deepcopy of the template), so this reads that shared
        geometry directly - only the returned array is scenario-specific.
    weirs: list of dicts from parse_weir_file, already in the mesh's CRS.
    tol: max distance [m] from a mesh-edge midpoint to a weir line to count
        as "on" the structure. Defaults to half the finest scale's median
        edge length (CDT-embedded edges sit almost exactly on the line, so
        this is generous headroom, not a fuzzy-matching threshold).

    Only the finest scale (the real SFINCS grid) gets nonzero values - a
    500-2000m coarse cell can't meaningfully represent a 2-20m barrier, and
    using a distance tolerance loose enough for coarse edges risks a coarse
    edge nowhere near the actual crossing falsely matching the line, then
    reading a km-averaged DEM as the "local terrain" (tried this: produced a
    242m "offset" at the coarsest scale on a 2m-crest scenario). Coarser
    scales still see the barrier indirectly through the model's existing
    coarse<->fine pooling edges during training.
    """
    from shapely.geometry import LineString, Point

    mesh = data.mesh
    assert hasattr(mesh, 'meshes'), "compute_edge_weir_crest_offset expects a MultiscaleMesh"

    lines_arcs = []
    for w in weirs:
        if len(w['xy']) < 2:
            continue
        seg = np.linalg.norm(np.diff(w['xy'], axis=0), axis=1)
        arc = np.concatenate([[0.0], np.cumsum(seg)])
        lines_arcs.append((LineString(w['xy']), arc, w['z']))

    if not lines_arcs:
        return np.zeros(data.edge_index.shape[1], dtype=np.float32)

    dem = data.DEM.numpy() if torch.is_tensor(data.DEM) else np.asarray(data.DEM)
    node_ptr = data.node_ptr.numpy() if torch.is_tensor(data.node_ptr) else np.asarray(data.node_ptr)

    finest_idx = max(range(len(mesh.meshes)), key=lambda i: mesh.meshes[i].num_faces)

    per_scale_offsets = []
    for scale_i, m in enumerate(mesh.meshes):
        n_edges_dual = m.dual_edge_index.shape[1]
        offset = np.zeros(n_edges_dual, dtype=np.float32)

        if scale_i != finest_idx:
            per_scale_offsets.append(offset)
            continue

        this_tol = tol if tol is not None else 0.5 * float(np.median(m.edge_length))
        local_dem = dem[node_ptr[scale_i]: node_ptr[scale_i + 1]]

        # primal edge (a, b) -> [face_i, face_j] sharing it, from face loops
        edge_to_faces = {}
        pos = 0
        for face_idx, n_nodes in enumerate(m.nodes_per_face):
            face_nodes = m.face_nodes[pos: pos + n_nodes]
            pos += n_nodes
            for k in range(n_nodes):
                a, b = int(face_nodes[k]), int(face_nodes[(k + 1) % n_nodes])
                edge_to_faces.setdefault(tuple(sorted((a, b))), []).append(face_idx)

        # sorted-face-pair -> every directed dual-edge column representing it
        # (dual_edge_index is made undirected, so both (f0,f1) and (f1,f0) exist)
        dual_lookup = {}
        for col, (f0, f1) in enumerate(m.dual_edge_index.T):
            dual_lookup.setdefault(tuple(sorted((int(f0), int(f1)))), []).append(col)

        for (a, b), faces in edge_to_faces.items():
            if len(faces) != 2:
                continue
            mid = Point(0.5 * (m.node_xy[a] + m.node_xy[b]))

            best_z, best_d = None, this_tol
            for line, arc, z_vals in lines_arcs:
                d = line.distance(mid)
                if d < best_d:
                    s = line.project(mid)
                    best_d, best_z = d, float(np.interp(s, arc, z_vals))

            if best_z is None:
                continue

            f0, f1 = faces
            crest_offset = max(0.0, best_z - 0.5 * (local_dem[f0] + local_dem[f1]))
            for col in dual_lookup.get(tuple(sorted((f0, f1))), []):
                offset[col] = crest_offset

        per_scale_offsets.append(offset)

    return np.concatenate(per_scale_offsets)


def build_output_data(template_data, WD, VX, VY,
                      map_times_s=None, src_xy=None, dis_times_s=None, discharge=None):
    data = copy.deepcopy(template_data)

    num_nodes = data.num_nodes if isinstance(data.num_nodes, int) else int(data.num_nodes)

    if WD.shape[0] != num_nodes or VX.shape[0] != num_nodes or VY.shape[0] != num_nodes:
        raise RuntimeError("Interpolated arrays do not match template num_nodes.")

    data.WD = torch.FloatTensor(WD)
    data.VX = torch.FloatTensor(VX)
    data.VY = torch.FloatTensor(VY)

    time_steps = WD.shape[1]

    if src_xy is not None and dis_times_s is not None and discharge is not None and map_times_s is not None:
        # Find nearest BOUNDARY face of the finest mesh level for each source point.
        # Use the mesh with the most faces as finest (robust to both coarse→fine and
        # fine→coarse orderings after invert_scale_ordering).
        if hasattr(data.mesh, 'meshes'):
            finest_idx = max(range(len(data.mesh.meshes)),
                             key=lambda i: data.mesh.meshes[i].num_faces)
            finest_mesh = data.mesh.meshes[finest_idx]
            finest_offset = int(data.node_ptr[finest_idx]) if hasattr(data, 'node_ptr') else 0
        else:
            finest_mesh = data.mesh
            finest_offset = 0
        if hasattr(finest_mesh, 'face_bnd') and len(finest_mesh.face_bnd) > 0:
            local_bnd_ids  = np.asarray(finest_mesh.face_bnd)
            global_bnd_ids = local_bnd_ids + finest_offset
            bnd_face_xy    = np.asarray(finest_mesh.face_xy)[local_bnd_ids]
            local_idx      = find_nearest_mesh_nodes(np.asarray(src_xy), bnd_face_xy)
            node_bc_indices = global_bnd_ids[local_idx].astype(np.int32)
            print(f"  Mapped {len(node_bc_indices)} source points to BOUNDARY mesh nodes: {node_bc_indices}")
        else:
            face_xy = np.asarray(data.mesh.face_xy)
            node_bc_indices = find_nearest_mesh_nodes(src_xy, face_xy)
            print(f"  Mapped {len(node_bc_indices)} source points to mesh nodes (fallback): {node_bc_indices}")
        n_bc = len(node_bc_indices)

        # Interpolate discharge from sfincs.dis time grid to map output times
        # discharge shape: [T_dis, n_src]
        bc_tensor = np.zeros((n_bc, time_steps, 2), dtype=np.float32)
        for i in range(n_bc):
            f_interp = interp1d(dis_times_s, discharge[:, i],
                                kind='linear', bounds_error=False,
                                fill_value=(discharge[0, i], discharge[-1, i]))
            # dataset.py reads BC[:,:,1] as the hydrograph — channel 0 is unused
            bc_tensor[i, :, 1] = f_interp(map_times_s).astype(np.float32)

        data.node_BC = torch.tensor(node_bc_indices, dtype=torch.int32)
        data.BC = torch.FloatTensor(bc_tensor)
        data.type_BC = torch.tensor(2, dtype=torch.int32)  # discharge type
        data.edge_BC_length = torch.ones(n_bc, dtype=torch.float32)
    else:
        # Fallback: preserve template BC structure, just resize time dimension
        if hasattr(data, "node_BC"):
            n_bc = int(data.node_BC.shape[0])
            data.BC = torch.zeros((n_bc, time_steps, 2), dtype=torch.float32)

    return data


def main():
    parser = argparse.ArgumentParser(description="Convert SFINCS map output to mSWE-GNN .pkl datasets")
    parser.add_argument("--sfincs-map", required=True, help="Path to sfincs_map.nc")
    parser.add_argument("--template-pkl", required=True, help="Path to template .pkl with mesh topology")
    parser.add_argument("--dataset-name", default="sfincs_marg", help="Output dataset name for train/test pkl")
    parser.add_argument("--out-root", default="database/datasets", help="Root dataset folder containing train/test")
    parser.add_argument("--x-var", default="x", help="x coordinate variable name")
    parser.add_argument("--y-var", default="y", help="y coordinate variable name")
    parser.add_argument("--water-level-var", default="zs", help="Water level variable name (surface elevation)")
    parser.add_argument("--bed-level-var", default="zb", help="Bed elevation variable name")
    parser.add_argument("--vx-var", default=None, help="Optional velocity-x variable name")
    parser.add_argument("--vy-var", default=None, help="Optional velocity-y variable name")
    parser.add_argument("--src-file", default=None, help="SFINCS source file (sfincs.src) with 7 source point locations")
    parser.add_argument("--dis-file", default=None, help="SFINCS discharge file (sfincs.dis) with time series")
    parser.add_argument("--weir-file", default=None,
                         help="SFINCS weir file (sfincs.weir) with crest elevations. If given, adds "
                              "edge_weir_crest to the output Data object (see compute_edge_weir_crest_offset). "
                              "Omit for simulations with no structures.")
    parser.add_argument("--only-var", choices=["WD", "VX", "VY"], default=None,
                         help="Compute only this variable's interpolation (the other two are filled with "
                              "zeros). Lets a caller split WD/VX/VY across separate process invocations - "
                              "running all three back-to-back in one process (~360 griddata/Qhull calls) "
                              "crashes unpredictably on some machines; a lone ~121-call run of just one "
                              "variable does not (see project_local_gpu_no_cuda memory). Orchestrated by "
                              "run_convert_structures.py, not needed for a normal single-process run.")
    args = parser.parse_args()

    if not os.path.exists(args.sfincs_map):
        raise FileNotFoundError(f"SFINCS map file not found: {args.sfincs_map}")
    if not os.path.exists(args.template_pkl):
        raise FileNotFoundError(f"Template .pkl not found: {args.template_pkl}")

    print("Loading template mesh...")
    template_data = load_single_data_object(args.template_pkl)
    target_points = get_target_points(template_data)
    print(f"  Target mesh nodes (faces): {target_points.shape[0]}")

    print("Opening SFINCS map...")
    ds = xr.open_dataset(args.sfincs_map, decode_times=False)

    if args.water_level_var not in ds.data_vars:
        raise RuntimeError(f"Water level variable '{args.water_level_var}' not found in sfincs_map.nc")
    if args.bed_level_var not in ds.data_vars:
        raise RuntimeError(f"Bed level variable '{args.bed_level_var}' not found in sfincs_map.nc")

    source_points = get_source_points(ds, x_var=args.x_var, y_var=args.y_var)
    print(f"  Source grid points: {source_points.shape[0]}")

    zs = ds[args.water_level_var].values  # [time, n, m]
    zb = ds[args.bed_level_var].values    # [n, m]

    if zs.ndim != 3 or zb.ndim != 2:
        raise RuntimeError("Expected zs [time,n,m] and zb [n,m].")

    # Map output time vector in seconds (used to interpolate discharge)
    time_var = ds.coords.get("time", ds.coords.get("t", None))
    if time_var is not None:
        map_times_s = time_var.values.astype(np.float64)
    else:
        map_times_s = np.arange(zs.shape[0], dtype=np.float64) * 3600.0
    print(f"  Map time steps: {len(map_times_s)}  ({map_times_s[0]:.0f}s – {map_times_s[-1]:.0f}s)")

    print("Computing water depth WD = max(zs - zb, 0)...")
    # SFINCS writes zs=NaN for DRY cells. Fill them with the bed level so they
    # enter the interpolation as WD=0. Without this, interpolate_time_series
    # drops the NaNs and linearly interpolates between wet cells only, smearing
    # phantom water across every dry area between wet river branches.
    zs_filled = np.where(np.isnan(zs), zb[None, :, :], zs)
    WD_grid = np.maximum(zs_filled - zb[None, :, :], 0.0).astype(np.float32)

    if args.only_var in (None, "WD"):
        print("Interpolating WD to mesh...")
        WD = interpolate_time_series(source_points, WD_grid, target_points, "WD")
    else:
        print(f"--only-var={args.only_var}: skipping WD, filling with zeros.")
        WD = np.zeros((target_points.shape[0], WD_grid.shape[0]), dtype=np.float32)

    # Velocities are optional in this SFINCS output. Use zeros if missing.
    # Open a second handle without xarray fill-value masking to avoid memory
    # allocation errors when SFINCS velocity vars have integer fill values.
    ds_raw = xr.open_dataset(args.sfincs_map, decode_times=False, mask_and_scale=False)

    if args.vx_var is not None and args.vx_var in ds.data_vars and args.only_var in (None, "VX"):
        print(f"Interpolating velocity X from '{args.vx_var}'...")
        VX_raw = ds_raw[args.vx_var].values.astype(np.float32)
        # Replace SFINCS fill values (typically large integers or -9999) with NaN
        fill_val = ds_raw[args.vx_var].attrs.get("_FillValue", None)
        if fill_val is not None:
            VX_raw[VX_raw == fill_val] = np.nan
        VX_grid = VX_raw
        VX = interpolate_time_series(source_points, VX_grid, target_points, "VX")
    else:
        VX = np.zeros_like(WD, dtype=np.float32)
        if args.only_var not in (None, "VX"):
            print(f"--only-var={args.only_var}: skipping VX, filling with zeros.")
        else:
            print("Velocity X not provided; using zeros.")

    if args.vy_var is not None and args.vy_var in ds.data_vars and args.only_var in (None, "VY"):
        print(f"Interpolating velocity Y from '{args.vy_var}'...")
        VY_raw = ds_raw[args.vy_var].values.astype(np.float32)
        fill_val = ds_raw[args.vy_var].attrs.get("_FillValue", None)
        if fill_val is not None:
            VY_raw[VY_raw == fill_val] = np.nan
        VY_grid = VY_raw
        VY = interpolate_time_series(source_points, VY_grid, target_points, "VY")
    else:
        VY = np.zeros_like(WD, dtype=np.float32)
        if args.only_var not in (None, "VY"):
            print(f"--only-var={args.only_var}: skipping VY, filling with zeros.")
        else:
            print("Velocity Y not provided; using zeros.")

    ds_raw.close()

    # Source BCs (optional)
    src_xy = dis_times_s = discharge = None
    if args.src_file and args.dis_file:
        print(f"Reading source points from {args.src_file}...")
        src_xy = parse_src_file(args.src_file)
        print(f"  {len(src_xy)} source points found.")
        print(f"Reading discharge from {args.dis_file}...")
        dis_times_s, discharge = parse_dis_file(args.dis_file)
        print(f"  Discharge shape: {discharge.shape}  time range: {dis_times_s[0]:.0f}s – {dis_times_s[-1]:.0f}s")
        if discharge.shape[1] != len(src_xy):
            raise RuntimeError(f"Discharge has {discharge.shape[1]} columns but src file has {len(src_xy)} points.")

    data_out = build_output_data(template_data, WD=WD, VX=VX, VY=VY,
                                 map_times_s=map_times_s, src_xy=src_xy,
                                 dis_times_s=dis_times_s, discharge=discharge)

    if args.weir_file:
        print(f"Reading weir crest elevations from {args.weir_file}...")
        weirs = parse_weir_file(args.weir_file)
        print(f"  {len(weirs)} weir line(s) found.")
        data_out.edge_weir_crest = torch.FloatTensor(compute_edge_weir_crest_offset(data_out, weirs))
        n_tagged = int((data_out.edge_weir_crest > 0).sum())
        print(f"  Tagged {n_tagged} dual edges with a nonzero crest offset "
              f"(max {float(data_out.edge_weir_crest.max()):.2f} m).")

    train_dir = os.path.join(args.out_root, "train")
    test_dir = os.path.join(args.out_root, "test")
    os.makedirs(train_dir, exist_ok=True)
    os.makedirs(test_dir, exist_ok=True)

    train_path = os.path.join(train_dir, f"{args.dataset_name}.pkl")
    test_path = os.path.join(test_dir, f"{args.dataset_name}.pkl")

    # Inference-only path: save same sample for train/test so scaler pipeline works.
    with open(train_path, "wb") as f:
        pickle.dump([data_out], f)
    with open(test_path, "wb") as f:
        pickle.dump([copy.deepcopy(data_out)], f)

    print("Done.")
    print(f"  Train dataset: {train_path}")
    print(f"  Test dataset:  {test_path}")
    print(f"  WD shape:      {tuple(data_out.WD.shape)}")
    print(f"  VX shape:      {tuple(data_out.VX.shape)}")
    print(f"  VY shape:      {tuple(data_out.VY.shape)}")


if __name__ == "__main__":
    main()
